baseURL = 'https://blog.abhishekan.dev/'
languageCode = 'en-us'
title = 'Abhishek AN'
theme = 'paper'

[params]
    # header social icons
    twitter = 'im_abhishekan'               # twitter.com/YOUR_TWITTER_ID
    github = 'DarkAbhi'                 # github.com/YOUR_GITHUB_ID
    instagram = 'iamabhishekan'           # instagram.com/YOUR_INSTAGRAM_ID
    linkedin = 'abhishek-an'             # linkedin.com/in/YOUR_LINKEDIN_ID
    
    name = 'Abhishek AN'
    bio = "Tech musings, travel stories, and life's adventures documented along the way."

    author = "Abhishek AN"

    avatar = 'https://avatars.githubusercontent.com/u/22658573?v=4'

    description = "Abhishek AN's portfolio â€“ exploring technology, startups, and community-driven initiatives."

    keywords = [
        "Abhishek AN",
        "Android engineer",
        "Software developer",
        "Full Stack Developer",
        "BigBasket",
        "Adevinta",
        "Appiness Interactive Pvt Ltd",
        "Xebia",
        "Terrum",
        "AgriApp",
        "HearthMath",
        "Appiness Interactive",
        "Tech communities",
        "Zero waste events"
    ]

    images = ["/images/og-image.png"]

    # icons (your head.html already uses these)
    favicon = "favicon.ico"
    appleTouchIcon = "apple-touch-icon.png"

    # Optional: extra Twitter info (we'll use this in head.html below)
    twitterSite = "@im_abhishekan"
    twitterCreator = "@im_abhishekan"